### ISSUE TITLE
Requires interactive-unity-plugin to Compile in Unity

### ISSUE THREAD

**Issue by gw1108** [mixer/chat-unity#1]
Downloading this project and opening it in Unity 2017.3.1f1 will have compiler errors. Probably because it's referencing things in the other github project interactive-unity-plugin. Would be nice to have an FYI in the readme.

**Comment by payzer** [comment]
Sorry I just saw this! Yes this would be good. I'll put it in.

**Comment by payzer** [comment]
Fixed! Thank you for reporting this.
